pipeline {
    // Joshua Warhurst A01238312 Set 4B
    // Exam Pipeline
    parameters {
        booleanParam(defaultValue: false, description: 'Run Target Scripts', name: 'TARGET')
    }
    agent any
    stages {
        stage('Build') {
                steps {
                    echo 'Running The Requirements'
                    sh 'pip install -r requirements.txt'
                    echo 'Requirements Complete'
                }
        }
        stage('Code Quality') {
                steps {
                    sh 'pylint --fail-under=5.0 *.py'
                }
            
        }
        stage('Code Quantity') {
                steps {
                    sh "find . -name '*.py' | xargs wc -l"
                }
        }
        stage('Run Scripts') {
            when {
                    expression { params.TARGET }
                }
                steps {
                    sh "python3 main.py phone text output"
                    sh "python3 main.py tablet csv output"
                    sh "python3 main.py laptop json output"
                }
        }
    }
}